FORMAT: 1A

# StartupGrid API

The StartupGrid API provides remote access to the StartupGrid DB of Posts, Authors, Users, Tags, Questions and Answers.

# Group Posts
A post is a web resource with some startup advice. There are three media types: blog posts, videos, and speaker decks.

## Posts Collection [/posts]
### List all Posts [GET]
+ Response 200 (application/json)

<!--         [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }] -->

## Post [/posts/{id}]
A single Post object with all its details
+ Parameters
    + id (required, number, `1`) ... Primary key of the post in question.

### Retrieve a Post [GET]
+ Response 200 (application/json)
    
    { "id": 2, "title": "Pick-up posters from post-office" }

# Group Authors

An author is the source of startup information. The listing contains a bio and links to external webpages on the author.

## Authors Collection [/authors]
### List All Authors [GET]

## Author Posts [/authors/{id}/posts]
### List Posts by Author [GET]

# Group Tags

A tag indicates the type of information in a post, and is related to posts through the "Taggings" model.

## Tags Collection [/tags]
### List All Tags [GET]

## Tag Posts [/tags/{id}/posts]
### List Posts by Tag [GET]
