# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

# Researchers
User.create(username: "ashley1", email: "kyleashley56@gmail.com", first: "Kyle", last: "Ashley", is_reviewer: true)
User.create(username: "williams2", email: "calvindenmark@gmail.com", first: "Calvin", last: "Denmark", is_reviewer: true)
User.create(username: "faber3", email: "zach.c.faber@gmail.com", first: "Zach", last: "Faber", is_reviewer: true)
User.create(username: "liu4", email: "lzliuyuan@gmail.com", first: "Yuan", last: "Liu", is_reviewer: true)
User.create(username: "frost", email: "cfrostgo@gmail.com", first: "Christopher", last: "Frost", is_reviewer: true)
User.create(username: "simmons6", email: "jamesksimmons1@gmail.com", first: "Jim", last: "Simmons", is_reviewer: true)
User.create(username: "milano7", email: "mpmilano9412@gmail.com", first: "Matt", last: "Milano", is_reviewer: true)
User.create(username: "culioli8", email: "raphael.culioli@gmail.com", first: "Raphael", last: "Culioli", is_reviewer: true)
User.create(username: "heidrich9", email: "pmheidrich@gmail.com", first: "Peter", last: "Heidrich", is_reviewer: true)
User.create(username: "wu10", email: "wufan3101@gmail.com", first: "Cathy", last: "Wu", is_reviewer: true)
User.create(username: "weissman11", email: "gabeweissman@gmail.com", first: "Gabe", last: "Weissman", is_reviewer: true)
User.create(username: "pesce12", email: "pescejoseph34@gmail.com", first: "Joe", last: "Pesce", is_reviewer: true)
User.create(username: "ngai13", email: "Dngai21@gmail.com", first: "Devon", last: "Ngai", is_reviewer: true)
User.create(username: "johri14", email: "anishjohri@gmail.com", first: "Anish", last: "Johri", is_reviewer: true)
User.create(username: "fessler15", email: "Leahfessler8@gmail.com", first: "Leah", last: "Fessler", is_reviewer: true)

# Tags
operations = Tag.create(name: "Operations", parent: nil, custom: false)
  administrative = Tag.create(parent: operations, custom: false, name: "Administrative")
    Tag.create(parent: administrative, custom: false, name: "Founders")
    Tag.create(parent: administrative, custom: false, name: "Office Space")
    Tag.create(parent: administrative, custom: false, name: "Geographic Location")
    Tag.create(parent: administrative, custom: false, name: "Employee Organization")
  compensation = Tag.create(parent: operations, custom: false, name: "Compensation")
    Tag.create(parent: compensation, custom: false, name: "Salaries")
    Tag.create(parent: compensation, custom: false, name: "Guidlines")
    Tag.create(parent: compensation, custom: false, name: "Stock Options")
    Tag.create(parent: compensation, custom: false, name: "Equity Structure")
    Tag.create(parent: compensation, custom: false, name: "Board Members")
    Tag.create(parent: compensation, custom: false, name: "Advisors ")
    Tag.create(parent: compensation, custom: false, name: "Investor Relations")
    Tag.create(parent: compensation, custom: false, name: "Contracts")
    Tag.create(parent: compensation, custom: false, name: "Fairness")
    Tag.create(parent: compensation, custom: false, name: "Founders")
  recruiting = Tag.create(parent: operations, custom: false, name: "Recruiting")
    Tag.create(parent: recruiting, custom: false, name: "Hiring")
    Tag.create(parent: recruiting, custom: false, name: "Venture Capital")
    Tag.create(parent: recruiting, custom: false, name: "Networking ")
    Tag.create(parent: recruiting, custom: false, name: "Outsourcing")
    Tag.create(parent: recruiting, custom: false, name: "Consultants")
    Tag.create(parent: recruiting, custom: false, name: "Positions")
    Tag.create(parent: recruiting, custom: false, name: "Culture")
    Tag.create(parent: recruiting, custom: false, name: "Work Ethic")
  product_and_design = Tag.create(parent: operations, custom: false, name: "Product & Deisgn")
    Tag.create(parent: product_and_design, custom: false, name: "Design")
    Tag.create(parent: product_and_design, custom: false, name: "UI/UX")
    Tag.create(parent: product_and_design, custom: false, name: "Conversion")
    Tag.create(parent: product_and_design, custom: false, name: "A/B Testing")
    Tag.create(parent: product_and_design, custom: false, name: "Copywriting")
    Tag.create(parent: product_and_design, custom: false, name: "Development")
    Tag.create(parent: product_and_design, custom: false, name: "Pricing")
    Tag.create(parent: product_and_design, custom: false, name: "Product Management")
    Tag.create(parent: product_and_design, custom: false, name: "Features")
    Tag.create(parent: product_and_design, custom: false, name: "User Engagement")
    Tag.create(parent: product_and_design, custom: false, name: "Usability")
    Tag.create(parent: product_and_design, custom: false, name: "Rapid Prototyping")
    Tag.create(parent: product_and_design, custom: false, name: "Beta")
    Tag.create(parent: product_and_design, custom: false, name: "Landing Page")

entrepreneurship = Tag.create(name: "Entrepreneurship", parent: nil, custom: false)
  pitching = Tag.create(parent: entrepreneurship, custom: false, name: "Pitching")
    Tag.create(parent: pitching, custom: false, name: "Security")
    Tag.create(parent: pitching, custom: false, name: "Timing ")
    Tag.create(parent: pitching, custom: false, name: "Preperation")
    Tag.create(parent: pitching, custom: false, name: "Demo")
    Tag.create(parent: pitching, custom: false, name: "Traction")
    Tag.create(parent: pitching, custom: false, name: "Business Model")
    Tag.create(parent: pitching, custom: false, name: "Mistakes")
    Tag.create(parent: pitching, custom: false, name: "Product")
    Tag.create(parent: pitching, custom: false, name: "Markets")
    Tag.create(parent: pitching, custom: false, name: "Recommendations")
  business_model = Tag.create(parent: entrepreneurship, custom: false, name: "Business Model")
    Tag.create(parent: business_model, custom: false, name: "Business Plan")
    Tag.create(parent: business_model, custom: false, name: "Saas")
    Tag.create(parent: business_model, custom: false, name: "B2B")
    Tag.create(parent: business_model, custom: false, name: "Pivoting")
    Tag.create(parent: business_model, custom: false, name: "NDA")
    Tag.create(parent: business_model, custom: false, name: "Investors")
    Tag.create(parent: business_model, custom: false, name: "Benefits")
    Tag.create(parent: business_model, custom: false, name: "Importance")
    Tag.create(parent: business_model, custom: false, name: "Agile")
    Tag.create(parent: business_model, custom: false, name: "Security")
  decks = Tag.create(parent: entrepreneurship, custom: false, name: "Decks")
    Tag.create(parent: decks, custom: false, name: "Investors ")
    Tag.create(parent: decks, custom: false, name: "Security")
    Tag.create(parent: decks, custom: false, name: "Benefits")
  education = Tag.create(parent: entrepreneurship, custom: false, name: "Education")
    Tag.create(parent: education, custom: false, name: "MBA")
    Tag.create(parent: education, custom: false, name: "Entrepreneur")
    Tag.create(parent: education, custom: false, name: "Programs")
    Tag.create(parent: education, custom: false, name: "Schools")
    Tag.create(parent: education, custom: false, name: "Majors")
  entrepreneurs = Tag.create(parent: entrepreneurship, custom: false, name: "Entrepreneurs")
    Tag.create(parent: entrepreneurs, custom: false, name: "Sucess ")
    Tag.create(parent: entrepreneurs, custom: false, name: "Investing")
    Tag.create(parent: entrepreneurs, custom: false, name: "Deal Terms")
    Tag.create(parent: entrepreneurs, custom: false, name: "Types")
    Tag.create(parent: entrepreneurs, custom: false, name: "Top Performers ")
    Tag.create(parent: entrepreneurs, custom: false, name: "Silicon Valley")
    Tag.create(parent: entrepreneurs, custom: false, name: "History")
    Tag.create(parent: entrepreneurs, custom: false, name: "Strengths")
    Tag.create(parent: entrepreneurs, custom: false, name: "Starting up")
    Tag.create(parent: entrepreneurs, custom: false, name: "Communities")
    Tag.create(parent: entrepreneurs, custom: false, name: "Networking")
    Tag.create(parent: entrepreneurs, custom: false, name: "Venture Capital")
    Tag.create(parent: entrepreneurs, custom: false, name: "Entrepreneurial Skills")
    Tag.create(parent: entrepreneurs, custom: false, name: "Founders")
    Tag.create(parent: entrepreneurs, custom: false, name: "Angels")
    Tag.create(parent: entrepreneurs, custom: false, name: "Lessons Learned")
    Tag.create(parent: entrepreneurs, custom: false, name: "Advice & Tips")
    Tag.create(parent: entrepreneurs, custom: false, name: "How to")
finance = Tag.create(name: "Finance", parent: nil, custom: false)
  accounting = Tag.create(parent: finance, custom: false, name: "Accounting")
    Tag.create(parent: accounting, custom: false, name: "Audits")
    Tag.create(parent: accounting, custom: false, name: "Financial Statements")
    Tag.create(parent: accounting, custom: false, name: "Cash Flow")
    Tag.create(parent: accounting, custom: false, name: "Valuation")
    Tag.create(parent: accounting, custom: false, name: "Limited Partners")
  capital = Tag.create(parent: finance, custom: false, name: "Capital")
    Tag.create(parent: capital, custom: false, name: "Efficiency")
    Tag.create(parent: capital, custom: false, name: "Lean")
    Tag.create(parent: capital, custom: false, name: "Burn Rate")
    Tag.create(parent: capital, custom: false, name: "Bootstrapping")
  debt = Tag.create(parent: finance, custom: false, name: "Debt")
    Tag.create(parent: debt, custom: false, name: "Timing")
    Tag.create(parent: debt, custom: false, name: "Conversion")
    Tag.create(parent: debt, custom: false, name: "Valuation")
    Tag.create(parent: debt, custom: false, name: "Valuation Cap")
    Tag.create(parent: debt, custom: false, name: "Warrants")
    Tag.create(parent: debt, custom: false, name: "Discounts")
    Tag.create(parent: debt, custom: false, name: "Seed Investment")
    Tag.create(parent: debt, custom: false, name: "Benefits")
    Tag.create(parent: debt, custom: false, name: "Alternatives")
    Tag.create(parent: debt, custom: false, name: "Venture Debt")
    Tag.create(parent: debt, custom: false, name: "Purpose")
    Tag.create(parent: debt, custom: false, name: "Size ")
    Tag.create(parent: debt, custom: false, name: "Stages")
  equity = Tag.create(parent: finance, custom: false, name: "Equity")
    Tag.create(parent: equity, custom: false, name: "Early Stage")
    Tag.create(parent: equity, custom: false, name: "Percentage")
    Tag.create(parent: equity, custom: false, name: "Employee Options")
    Tag.create(parent: equity, custom: false, name: "Stock Options")
    Tag.create(parent: equity, custom: false, name: "Ranges")
    Tag.create(parent: equity, custom: false, name: "Dilution")
    Tag.create(parent: equity, custom: false, name: "Rounds")
    Tag.create(parent: equity, custom: false, name: "Cost")
    Tag.create(parent: equity, custom: false, name: "Benefit")
    Tag.create(parent: equity, custom: false, name: "Stages")
  revenue_model = Tag.create(parent: finance, custom: false, name: "Revenue Model")
    Tag.create(parent: revenue_model, custom: false, name: "Revenue Model")
    Tag.create(parent: revenue_model, custom: false, name: "Freemium")
    Tag.create(parent: revenue_model, custom: false, name: "Advertisment")
    Tag.create(parent: revenue_model, custom: false, name: "Subscription")
strategy = Tag.create(name: "Strategy", parent: nil, custom: false)
  competition = Tag.create(parent: strategy, custom: false, name: "Competition")
    Tag.create(parent: competition, custom: false, name: "Venture Capital Portfolio")
    Tag.create(parent: competition, custom: false, name: "Market Share")
    Tag.create(parent: competition, custom: false, name: "Differentiation")
  customer_development = Tag.create(parent: strategy, custom: false, name: "Customer Development")
    Tag.create(parent: customer_development, custom: false, name: "Customer Relationship")
    Tag.create(parent: customer_development, custom: false, name: "Customer Base")
    Tag.create(parent: customer_development, custom: false, name: "Minimal Viable Product")
    Tag.create(parent: customer_development, custom: false, name: "Feedback")
    Tag.create(parent: customer_development, custom: false, name: "Early Adopters")
    Tag.create(parent: customer_development, custom: false, name: "Data")
    Tag.create(parent: customer_development, custom: false, name: "Product")
    Tag.create(parent: customer_development, custom: false, name: "Market Fit ")
    Tag.create(parent: customer_development, custom: false, name: "Market Share")
    Tag.create(parent: customer_development, custom: false, name: "Product to Market")
    Tag.create(parent: customer_development, custom: false, name: "Costs")
    Tag.create(parent: customer_development, custom: false, name: "Customer Aquisition")
    Tag.create(parent: customer_development, custom: false, name: "Validation")
    Tag.create(parent: customer_development, custom: false, name: "Monetization")
    Tag.create(parent: customer_development, custom: false, name: "Experiments")
    Tag.create(parent: customer_development, custom: false, name: "Scrum")
    Tag.create(parent: customer_development, custom: false, name: "Customer Experience")
    Tag.create(parent: customer_development, custom: false, name: "Customer Support")
  starting_up = Tag.create(parent: strategy, custom: false, name: "Starting up")
    Tag.create(parent: starting_up, custom: false, name: "Experiments")
    Tag.create(parent: starting_up, custom: false, name: "Stealth")
    Tag.create(parent: starting_up, custom: false, name: "Brand Name")
    Tag.create(parent: starting_up, custom: false, name: "Investment Readiness")
    Tag.create(parent: starting_up, custom: false, name: "Open Meetings")
    Tag.create(parent: starting_up, custom: false, name: "Hypothesis Testing")
    Tag.create(parent: starting_up, custom: false, name: "Blogs")
    Tag.create(parent: starting_up, custom: false, name: "Idea Investor")
    Tag.create(parent: starting_up, custom: false, name: "Early Principles")
    Tag.create(parent: starting_up, custom: false, name: "Strategy")
    Tag.create(parent: starting_up, custom: false, name: "Early Stage")
    Tag.create(parent: starting_up, custom: false, name: "Definition")
    Tag.create(parent: starting_up, custom: false, name: "Risks")
    Tag.create(parent: starting_up, custom: false, name: "Launching")
    Tag.create(parent: starting_up, custom: false, name: "Transparency")
    Tag.create(parent: starting_up, custom: false, name: "Employees")
    Tag.create(parent: starting_up, custom: false, name: "Business Model")
    Tag.create(parent: starting_up, custom: false, name: "Funding")
    Tag.create(parent: starting_up, custom: false, name: "Starting")
    Tag.create(parent: starting_up, custom: false, name: "Failing")
    Tag.create(parent: starting_up, custom: false, name: "Scrum")
    Tag.create(parent: starting_up, custom: false, name: "Case Studies")
  lean = Tag.create(parent: strategy, custom: false, name: "Lean")
    Tag.create(parent: lean, custom: false, name: "Definition")
    Tag.create(parent: lean, custom: false, name: "Strategy")
    Tag.create(parent: lean, custom: false, name: "Expense")
    Tag.create(parent: lean, custom: false, name: "Efficiency")
    Tag.create(parent: lean, custom: false, name: "Experimental Learning")
    Tag.create(parent: lean, custom: false, name: "Theoretical Learning")
    Tag.create(parent: lean, custom: false, name: "Performance")
  growth = Tag.create(parent: strategy, custom: false, name: "Growth")
    Tag.create(parent: growth, custom: false, name: "Management")
    Tag.create(parent: growth, custom: false, name: "Scaling")
    Tag.create(parent: growth, custom: false, name: "Speed")
    Tag.create(parent: growth, custom: false, name: "Timing")
    Tag.create(parent: growth, custom: false, name: "Consequences")
    Tag.create(parent: growth, custom: false, name: "Growth Hacking")
venture_funding = Tag.create(name: "Venture Funding", parent: nil, custom: false)
  angels = Tag.create(parent: venture_funding, custom: false, name: "Angels")
    Tag.create(parent: angels, custom: false, name: "Transparency")
    Tag.create(parent: angels, custom: false, name: "Investor Relations")
    Tag.create(parent: angels, custom: false, name: "Investment Type")
    Tag.create(parent: angels, custom: false, name: "Investment Size")
    Tag.create(parent: angels, custom: false, name: "Benefits")
    Tag.create(parent: angels, custom: false, name: "Venture Capital")
    Tag.create(parent: angels, custom: false, name: "Lead Investor")
    Tag.create(parent: angels, custom: false, name: "Raising Capital")
    Tag.create(parent: angels, custom: false, name: "Networking")
    Tag.create(parent: angels, custom: false, name: "Rounds")
  exits = Tag.create(parent: venture_funding, custom: false, name: "Exits")
    Tag.create(parent: exits, custom: false, name: "Investors")
    Tag.create(parent: exits, custom: false, name: "CEO")
    Tag.create(parent: exits, custom: false, name: "Hiring")
    Tag.create(parent: exits, custom: false, name: "Employee")
    Tag.create(parent: exits, custom: false, name: "Founders")
    Tag.create(parent: exits, custom: false, name: "Intellectual Property")
    Tag.create(parent: exits, custom: false, name: "Stock Options")
    Tag.create(parent: exits, custom: false, name: "Equity")
    Tag.create(parent: exits, custom: false, name: "Failing")
    Tag.create(parent: exits, custom: false, name: "Profit")
    Tag.create(parent: exits, custom: false, name: "Acquisition")
    Tag.create(parent: exits, custom: false, name: "IPO")
    Tag.create(parent: exits, custom: false, name: "Buyout")
    Tag.create(parent: exits, custom: false, name: "Mergers")
  fundraising = Tag.create(parent: venture_funding, custom: false, name: "Fundraising")
    Tag.create(parent: fundraising, custom: false, name: "Timing ")
    Tag.create(parent: fundraising, custom: false, name: "Reimbursment")
    Tag.create(parent: fundraising, custom: false, name: "Costs")
    Tag.create(parent: fundraising, custom: false, name: "Firms")
    Tag.create(parent: fundraising, custom: false, name: "Company Classification")
    Tag.create(parent: fundraising, custom: false, name: "Bids")
    Tag.create(parent: fundraising, custom: false, name: "Rejection")
    Tag.create(parent: fundraising, custom: false, name: "Confidence")
    Tag.create(parent: fundraising, custom: false, name: "Benefits")
    Tag.create(parent: fundraising, custom: false, name: "Rounds")
    Tag.create(parent: fundraising, custom: false, name: "Investor Types")
    Tag.create(parent: fundraising, custom: false, name: "Angels")
    Tag.create(parent: fundraising, custom: false, name: "VCs")
  investment = Tag.create(parent: venture_funding, custom: false, name: "Investment")
    Tag.create(parent: investment, custom: false, name: "Investment Readiness")
    Tag.create(parent: investment, custom: false, name: "Founder")
  valuation = Tag.create(parent: venture_funding, custom: false, name: "Valuation")
    Tag.create(parent: valuation, custom: false, name: "Value Proposition")
    Tag.create(parent: valuation, custom: false, name: "Financial Statements")
    Tag.create(parent: valuation, custom: false, name: "Venture Capital Valuation")
    Tag.create(parent: valuation, custom: false, name: "Discount")
    Tag.create(parent: valuation, custom: false, name: "Early Stage")
    Tag.create(parent: valuation, custom: false, name: "Pre-Launch")
  mergers_and_acquisitions = Tag.create(parent: venture_funding, custom: false, name: "M&A")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Shareholder Representative")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Audited Financails")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Founders")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Debt")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Valuation")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Fairness")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Offer")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Management Carve Out")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Mergers")
    Tag.create(parent: mergers_and_acquisitions, custom: false, name: "Planning")
  negotiation = Tag.create(parent: venture_funding, custom: false, name: "Negotiation")
    Tag.create(parent: negotiation, custom: false, name: "Investor Relations")
    Tag.create(parent: negotiation, custom: false, name: "Fairness")
  terms = Tag.create(parent: venture_funding, custom: false, name: "Terms")
    Tag.create(parent: terms, custom: false, name: "Rounds")
    Tag.create(parent: terms, custom: false, name: "Angels")
    Tag.create(parent: terms, custom: false, name: "Pro-Rata Rights")
    Tag.create(parent: terms, custom: false, name: "Dilution")
    Tag.create(parent: terms, custom: false, name: "Equity")
    Tag.create(parent: terms, custom: false, name: "Founders")
    Tag.create(parent: terms, custom: false, name: "Mistakes")
    Tag.create(parent: terms, custom: false, name: "Reccomendations")
    Tag.create(parent: terms, custom: false, name: "Venture Capital")
leadership_and_management = Tag.create(name: "Leadership & Management", parent: nil, custom: false)
  advisors = Tag.create(parent: leadership_and_management, custom: false, name: "Advisors")
    Tag.create(parent: advisors, custom: false, name: "Benefits")
    Tag.create(parent: advisors, custom: false, name: "Role")
    Tag.create(parent: advisors, custom: false, name: "Sourcing")
    Tag.create(parent: advisors, custom: false, name: "Compensation")
    Tag.create(parent: advisors, custom: false, name: "Resume")
    Tag.create(parent: advisors, custom: false, name: "Termination")
    Tag.create(parent: advisors, custom: false, name: "Mentorship")
    Tag.create(parent: advisors, custom: false, name: "Networking ")
  board_of_directors = Tag.create(parent: leadership_and_management, custom: false, name: "Board of Directors")
    Tag.create(parent: board_of_directors, custom: false, name: "Equity")
    Tag.create(parent: board_of_directors, custom: false, name: "Role")
    Tag.create(parent: board_of_directors, custom: false, name: "Timing")
    Tag.create(parent: board_of_directors, custom: false, name: "Benefits")
    Tag.create(parent: board_of_directors, custom: false, name: "Types")
    Tag.create(parent: board_of_directors, custom: false, name: "Meetings")
    Tag.create(parent: board_of_directors, custom: false, name: "Compensation")
  introductions = Tag.create(parent: leadership_and_management, custom: false, name: "Introductions")
    Tag.create(parent: introductions, custom: false, name: "Investors")
    Tag.create(parent: introductions, custom: false, name: "Angels")
    Tag.create(parent: introductions, custom: false, name: "Networking")
    Tag.create(parent: introductions, custom: false, name: "Meetings")
    Tag.create(parent: introductions, custom: false, name: "Pitching")
    Tag.create(parent: introductions, custom: false, name: "Strategy")
  founders = Tag.create(parent: leadership_and_management, custom: false, name: "Founders")
    Tag.create(parent: founders, custom: false, name: "CEO")
    Tag.create(parent: founders, custom: false, name: "Effectiveness")
    Tag.create(parent: founders, custom: false, name: "Exit")
    Tag.create(parent: founders, custom: false, name: "CoFounder")
    Tag.create(parent: founders, custom: false, name: "Founding Team")
    Tag.create(parent: founders, custom: false, name: "Skills")
    Tag.create(parent: founders, custom: false, name: "Expertise")
    Tag.create(parent: founders, custom: false, name: "Transparency")
    Tag.create(parent: founders, custom: false, name: "Equity")
    Tag.create(parent: founders, custom: false, name: "Types")
  management = Tag.create(parent: leadership_and_management, custom: false, name: "Management")
    Tag.create(parent: management, custom: false, name: "Team Quality")
    Tag.create(parent: management, custom: false, name: "Venture Capital")
    Tag.create(parent: management, custom: false, name: "Types")
    Tag.create(parent: management, custom: false, name: "Team Investment")
    Tag.create(parent: management, custom: false, name: "Organization")
    Tag.create(parent: management, custom: false, name: "Culture")
    Tag.create(parent: management, custom: false, name: "Productivity")
marketing_and_sales = Tag.create(name: "Marketing & Sales", parent: nil, custom: false)
  marketing = Tag.create(parent: marketing_and_sales, custom: false, name: "Marketing")
    Tag.create(parent: marketing, custom: false, name: "Early Stage")
    Tag.create(parent: marketing, custom: false, name: "Branding")
    Tag.create(parent: marketing, custom: false, name: "Launching")
    Tag.create(parent: marketing, custom: false, name: "Cost")
    Tag.create(parent: marketing, custom: false, name: "Benefits")
    Tag.create(parent: marketing, custom: false, name: "Product Marketing")
    Tag.create(parent: marketing, custom: false, name: "Market Fit")
    Tag.create(parent: marketing, custom: false, name: "Product Market Fit")
    Tag.create(parent: marketing, custom: false, name: "Outsourcing")
    Tag.create(parent: marketing, custom: false, name: "Public Relations")
    Tag.create(parent: marketing, custom: false, name: "Media")
    Tag.create(parent: marketing, custom: false, name: "Social Media")
    Tag.create(parent: marketing, custom: false, name: "Advertising")
    Tag.create(parent: marketing, custom: false, name: "Growth Hacking")
    Tag.create(parent: marketing, custom: false, name: "SEO")
    Tag.create(parent: marketing, custom: false, name: "Inbound Marketing")
    Tag.create(parent: marketing, custom: false, name: "Blogging")
    Tag.create(parent: marketing, custom: false, name: "Content Marketing")
    Tag.create(parent: marketing, custom: false, name: "Community Management")
    Tag.create(parent: marketing, custom: false, name: "Content Development")
    Tag.create(parent: marketing, custom: false, name: "Launch")
  sales = Tag.create(parent: marketing_and_sales, custom: false, name: "Sales")
    Tag.create(parent: sales, custom: false, name: "Growth Hacking")
    Tag.create(parent: sales, custom: false, name: "Customer Acquisition")
    Tag.create(parent: sales, custom: false, name: "Launch")
    Tag.create(parent: sales, custom: false, name: "Competition")
    Tag.create(parent: sales, custom: false, name: "Sales")
legal = Tag.create(name: "Legal", parent: nil, custom: false)
  legal_lawyers = Tag.create(parent: legal, custom: false, name: "Legal/Lawyers")
    Tag.create(parent: legal_lawyers, custom: false, name: "Benefits")
    Tag.create(parent: legal_lawyers, custom: false, name: "Cost")
    Tag.create(parent: legal_lawyers, custom: false, name: "Law Firm")
    Tag.create(parent: legal_lawyers, custom: false, name: "Reccomendations")
    Tag.create(parent: legal_lawyers, custom: false, name: "Equity")
    Tag.create(parent: legal_lawyers, custom: false, name: "Investor Fees")
    Tag.create(parent: legal_lawyers, custom: false, name: "Advisors")
    Tag.create(parent: legal_lawyers, custom: false, name: "NDA")
  intellectual_property = Tag.create(parent: legal, custom: false, name: "Intellectual Property")
    Tag.create(parent: intellectual_property, custom: false, name: "Benefit")
    Tag.create(parent: intellectual_property, custom: false, name: "Cost")
    Tag.create(parent: intellectual_property, custom: false, name: "Investor Relations")
    Tag.create(parent: intellectual_property, custom: false, name: "Patents")
    Tag.create(parent: intellectual_property, custom: false, name: "Stealing")
