# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(username: nil, email: "colander@middlebury.edu", first: "David", last: "Colander", is_reviewer: true)
User.create(username: nil, email: "ty@tydanco.com", first: "Ty", last: "Danco", is_reviewer: true)
User.create(username: nil, email: "adam@agilion.com", first: "Adam", last: "Bouchard", is_reviewer: true)
User.create(username: nil, email: "jvacovex@gmail.com", first: "Jake", last: "Vacovec", is_reviewer: true)
User.create(username: nil, email: "mhhuebsch@gmail.com", first: "Hunter", last: "Huebsch", is_reviewer: true)
User.create(username: nil, email: "teddyknox@gmail.com", first: "Teddy", last: "Knox", is_reviewer: true)
User.create(username: nil, email: "willstonepotter@gmail.com", first: "Will", last: "Potter", is_reviewer: true)
User.create(username: nil, email: "benweaver136@gmail.com", first: "Ben", last: "Weaver", is_reviewer: true)
User.create(username: nil, email: "wthanley@gmail.com", first: "Will", last: "Hanley", is_reviewer: true)
User.create(username: nil, email: "sarahbmacy@gmail.com", first: "Sarah", last: "Macy", is_reviewer: true)
User.create(username: nil, email: "kahnchad@gmail.com", first: "Chad", last: "Kahn", is_reviewer: true)
User.create(username: nil, email: "christianbonaventura8@gmail.com", first: "Christian", last: "Bonaventura", is_reviewer: true)
User.create(username: nil, email: "kyleashley56@gmail.com", first: "Kyle", last: "Ashley", is_reviewer: true)
User.create(username: nil, email: "calvindenmark@gmail.com", first: "Calvin", last: "Denmark", is_reviewer: true)
User.create(username: nil, email: "zach.c.faber@gmail.com", first: "Zach", last: "Faber", is_reviewer: true)
User.create(username: nil, email: "lzliuyuan@gmail.com", first: "Yuan", last: "Liu", is_reviewer: true)
User.create(username: nil, email: "cfrostgo@gmail.com", first: "Christopher", last: "Frost", is_reviewer: true)
User.create(username: nil, email: "jamesksimmons1@gmail.com", first: "Jim", last: "Simmons", is_reviewer: true)
User.create(username: nil, email: "mpmilano9412@gmail.com", first: "Matt", last: "Milano", is_reviewer: true)
User.create(username: nil, email: "raphael.culioli@gmail.com", first: "Raphael", last: "Culioli", is_reviewer: true)
User.create(username: nil, email: "pmheidrich@gmail.com", first: "Peter", last: "Heidrich", is_reviewer: true)
User.create(username: nil, email: "wufan3101@gmail.com", first: "Cathy", last: "Wu", is_reviewer: true)
User.create(username: nil, email: "gabeweissman@gmail.com", first: "Gabe", last: "Weissman", is_reviewer: true)
User.create(username: nil, email: "pescejoseph34@gmail.com", first: "Joe", last: "Pesce", is_reviewer: true)
User.create(username: nil, email: "Dngai21@gmail.com", first: "Devon", last: "Ngai", is_reviewer: true)
User.create(username: nil, email: "anishjohri@gmail.com", first: "Anish", last: "Johri", is_reviewer: true)
User.create(username: nil, email: "Leahfessler8@gmail.com", first: "Leah", last: "Fessler", is_reviewer: true)
User.create(username: nil, email: "abhattacharya6392@gmail.com", first: "Annesha", last: "Bhattacharya", is_reviewer: true)